English:
  font1: Noto/English/Montserrat-Bold.ttf
  font2: Noto/English/Montserrat-Regular.ttf
  size1: 30
  size2: 26
English_title:
  font: Noto/English/Montserrat-Bold.ttf
  size: 34
Gujarati:
  font1: Noto/Gujarati/NotoSansGujarati-Bold.ttf
  font2: Noto/Gujarati/NotoSansGujarati-Regular.ttf
  size1: 30
  size2: 40
Hindi:
  font1: Noto/Devanagari/NotoSansDevanagari-Bold.ttf
  font2: Noto/Devanagari/NotoSansDevanagari-Regular.ttf
  size1: 30
  size2: 40
Kannada:
  font1: Noto/Kannada/NotoSansKannada-Bold.ttf
  font2: Noto/Kannada/NotoSansKannada-Regular.ttf
  size1: 30
  size2: 37
Khasi:
  font1: Noto/English/Montserrat-Bold.ttf
  font2: Noto/English/Montserrat-Regular.ttf
  size1: 30
  size2: 33
Konkani:
  font1: Noto/Devanagari/NotoSansDevanagari-Bold.ttf
  font2: Noto/Devanagari/NotoSansDevanagari-Regular.ttf
  size1: 30
  size2: 37
Malayalam:
  font1: Noto/Malayalam/NotoSansMalayalam-Bold.ttf
  font2: Noto/Malayalam/NotoSansMalayalam-Regular.ttf
  size1: 26
  size2: 32
Manipuri:
  font1: Noto/Bengali/NotoSansBengali-Bold.ttf
  font2: Noto/Bengali/NotoSansBengali-Regular.ttf
  size1: 30
  size2: 40
Manipuri_meitei:
  font1: Noto/EyekPro-Regular.ttf
  font2: Noto/EyekPro-Regular.ttf
  size1: 30
  size2: 32
Marathi:
  font1: Noto/Devanagari/NotoSansDevanagari-Bold.ttf
  font2: Noto/Devanagari/NotoSansDevanagari-Regular.ttf
  size1: 40
  size2: 25
Nepali:
  font1: Noto/Devanagari/NotoSansDevanagari-Bold.ttf
  font2: Noto/Devanagari/NotoSansDevanagari-Regular.ttf
  size1: 30
  size2: 40
Odia:
  font1: Noto/Odia/NotoSansOriya-Bold.ttf
  font2: Noto/Odia/NotoSansOriya-Regular.ttf
  size1: 30
  size2: 34
Portuguese:
  font1: Noto/English/Montserrat-Bold.ttf
  font2: Noto/English/Montserrat-Regular.ttf
  size1: 30
  size2: 34
Punjabi:
  font1: Noto/Punjabi/NotoSansGurmukhi-Bold.ttf
  font2: Noto/Punjabi/NotoSansGurmukhi-Regular.ttf
  size1: 30
  size2: 38
Tamil:
  font1: Noto/Tamil/NotoSansTamil-Bold.ttf
  font2: Noto/Tamil/NotoSansTamil-Regular.ttf
  size1: 30
  size2: 21
Telugu:
  font1: Noto/Telugu/NotoSansTelugu-Bold.ttf
  font2: Noto/Telugu/NotoSansTelugu-Regular.ttf
  size1: 30
  size2: 26
Urdu:
  font1: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf
  font2: Noto/Urdu/NotoNastaliqUrdu-Regular.ttf
  size1: 27
  size2: 23
